//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml.mathml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.isi.bmkeg.lapdf.pmcXml.mathml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Xor_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "xor");
    private final static QName _Max_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "max");
    private final static QName _Min_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "min");
    private final static QName _Arctan_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arctan");
    private final static QName _Leq_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "leq");
    private final static QName _Divide_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "divide");
    private final static QName _True_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "true");
    private final static QName _Product_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "product");
    private final static QName _Arcsin_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arcsin");
    private final static QName _Csc_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "csc");
    private final static QName _Sec_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "sec");
    private final static QName _Sin_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "sin");
    private final static QName _Factorial_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "factorial");
    private final static QName _Primes_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "primes");
    private final static QName _Rem_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "rem");
    private final static QName _Exists_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "exists");
    private final static QName _Emptyset_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "emptyset");
    private final static QName _Arccosh_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arccosh");
    private final static QName _Eq_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "eq");
    private final static QName _Gcd_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "gcd");
    private final static QName _Imaginaryi_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "imaginaryi");
    private final static QName _Equivalent_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "equivalent");
    private final static QName _Ln_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "ln");
    private final static QName _Implies_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "implies");
    private final static QName _Imaginary_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "imaginary");
    private final static QName _Lt_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "lt");
    private final static QName _Neq_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "neq");
    private final static QName _Sum_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "sum");
    private final static QName _Infinity_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "infinity");
    private final static QName _Arcsech_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arcsech");
    private final static QName _Approx_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "approx");
    private final static QName _Real_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "real");
    private final static QName _Ident_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "ident");
    private final static QName _Times_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "times");
    private final static QName _Domain_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "domain");
    private final static QName _Arccoth_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arccoth");
    private final static QName _Csch_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "csch");
    private final static QName _Minus_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "minus");
    private final static QName _Cosh_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "cosh");
    private final static QName _Geq_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "geq");
    private final static QName _Plus_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "plus");
    private final static QName _Or_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "or");
    private final static QName _Arccsch_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arccsch");
    private final static QName _Sech_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "sech");
    private final static QName _Arctanh_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arctanh");
    private final static QName _Sinh_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "sinh");
    private final static QName _Image_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "image");
    private final static QName _Arccsc_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arccsc");
    private final static QName _Factorof_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "factorof");
    private final static QName _And_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "and");
    private final static QName _Exponentiale_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "exponentiale");
    private final static QName _Conjugate_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "conjugate");
    private final static QName _Forall_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "forall");
    private final static QName _Log_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "log");
    private final static QName _Not_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "not");
    private final static QName _Exp_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "exp");
    private final static QName _Floor_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "floor");
    private final static QName _Ceiling_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "ceiling");
    private final static QName _Rationals_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "rationals");
    private final static QName _Gt_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "gt");
    private final static QName _Tan_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "tan");
    private final static QName _Pi_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "pi");
    private final static QName _Coth_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "coth");
    private final static QName _Integers_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "integers");
    private final static QName _Complexes_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "complexes");
    private final static QName _Arcsinh_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arcsinh");
    private final static QName _Quotient_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "quotient");
    private final static QName _Arccot_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arccot");
    private final static QName _Arccos_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arccos");
    private final static QName _Cos_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "cos");
    private final static QName _Root_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "root");
    private final static QName _Cot_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "cot");
    private final static QName _Reals_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "reals");
    private final static QName _Naturalnumbers_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "naturalnumbers");
    private final static QName _Lcm_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "lcm");
    private final static QName _Abs_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "abs");
    private final static QName _Tanh_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "tanh");
    private final static QName _Notanumber_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "notanumber");
    private final static QName _Arg_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arg");
    private final static QName _Arcsec_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "arcsec");
    private final static QName _Codomain_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "codomain");
    private final static QName _Compose_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "compose");
    private final static QName _Power_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "power");
    private final static QName _False_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "false");
    private final static QName _Eulergamma_QNAME = new QName("http://www.w3.org/1998/Math/MathML", "eulergamma");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.isi.bmkeg.lapdf.pmcXml.mathml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PmcXmlMath }
     * 
     */
    public PmcXmlMath createPmcXmlMath() {
        return new PmcXmlMath();
    }

    /**
     * Create an instance of {@link PmcXmlMi }
     * 
     */
    public PmcXmlMi createPmcXmlMi() {
        return new PmcXmlMi();
    }

    /**
     * Create an instance of {@link PmcXmlMalignmark }
     * 
     */
    public PmcXmlMalignmark createPmcXmlMalignmark() {
        return new PmcXmlMalignmark();
    }

    /**
     * Create an instance of {@link PmcXmlMglyph }
     * 
     */
    public PmcXmlMglyph createPmcXmlMglyph() {
        return new PmcXmlMglyph();
    }

    /**
     * Create an instance of {@link PmcXmlMo }
     * 
     */
    public PmcXmlMo createPmcXmlMo() {
        return new PmcXmlMo();
    }

    /**
     * Create an instance of {@link PmcXmlMn }
     * 
     */
    public PmcXmlMn createPmcXmlMn() {
        return new PmcXmlMn();
    }

    /**
     * Create an instance of {@link PmcXmlMtext }
     * 
     */
    public PmcXmlMtext createPmcXmlMtext() {
        return new PmcXmlMtext();
    }

    /**
     * Create an instance of {@link PmcXmlMs }
     * 
     */
    public PmcXmlMs createPmcXmlMs() {
        return new PmcXmlMs();
    }

    /**
     * Create an instance of {@link PmcXmlMrow }
     * 
     */
    public PmcXmlMrow createPmcXmlMrow() {
        return new PmcXmlMrow();
    }

    /**
     * Create an instance of {@link PmcXmlMfrac }
     * 
     */
    public PmcXmlMfrac createPmcXmlMfrac() {
        return new PmcXmlMfrac();
    }

    /**
     * Create an instance of {@link PmcXmlMsqrt }
     * 
     */
    public PmcXmlMsqrt createPmcXmlMsqrt() {
        return new PmcXmlMsqrt();
    }

    /**
     * Create an instance of {@link PmcXmlMroot }
     * 
     */
    public PmcXmlMroot createPmcXmlMroot() {
        return new PmcXmlMroot();
    }

    /**
     * Create an instance of {@link PmcXmlMpadded }
     * 
     */
    public PmcXmlMpadded createPmcXmlMpadded() {
        return new PmcXmlMpadded();
    }

    /**
     * Create an instance of {@link PmcXmlMphantom }
     * 
     */
    public PmcXmlMphantom createPmcXmlMphantom() {
        return new PmcXmlMphantom();
    }

    /**
     * Create an instance of {@link PmcXmlMfenced }
     * 
     */
    public PmcXmlMfenced createPmcXmlMfenced() {
        return new PmcXmlMfenced();
    }

    /**
     * Create an instance of {@link PmcXmlMenclose }
     * 
     */
    public PmcXmlMenclose createPmcXmlMenclose() {
        return new PmcXmlMenclose();
    }

    /**
     * Create an instance of {@link PmcXmlMsub }
     * 
     */
    public PmcXmlMsub createPmcXmlMsub() {
        return new PmcXmlMsub();
    }

    /**
     * Create an instance of {@link PmcXmlMsup }
     * 
     */
    public PmcXmlMsup createPmcXmlMsup() {
        return new PmcXmlMsup();
    }

    /**
     * Create an instance of {@link PmcXmlMsubsup }
     * 
     */
    public PmcXmlMsubsup createPmcXmlMsubsup() {
        return new PmcXmlMsubsup();
    }

    /**
     * Create an instance of {@link PmcXmlMunder }
     * 
     */
    public PmcXmlMunder createPmcXmlMunder() {
        return new PmcXmlMunder();
    }

    /**
     * Create an instance of {@link PmcXmlMover }
     * 
     */
    public PmcXmlMover createPmcXmlMover() {
        return new PmcXmlMover();
    }

    /**
     * Create an instance of {@link PmcXmlMunderover }
     * 
     */
    public PmcXmlMunderover createPmcXmlMunderover() {
        return new PmcXmlMunderover();
    }

    /**
     * Create an instance of {@link PmcXmlMmultiscripts }
     * 
     */
    public PmcXmlMmultiscripts createPmcXmlMmultiscripts() {
        return new PmcXmlMmultiscripts();
    }

    /**
     * Create an instance of {@link PmcXmlMtable }
     * 
     */
    public PmcXmlMtable createPmcXmlMtable() {
        return new PmcXmlMtable();
    }

    /**
     * Create an instance of {@link PmcXmlMtr }
     * 
     */
    public PmcXmlMtr createPmcXmlMtr() {
        return new PmcXmlMtr();
    }

    /**
     * Create an instance of {@link PmcXmlMtd }
     * 
     */
    public PmcXmlMtd createPmcXmlMtd() {
        return new PmcXmlMtd();
    }

    /**
     * Create an instance of {@link PmcXmlMaligngroup }
     * 
     */
    public PmcXmlMaligngroup createPmcXmlMaligngroup() {
        return new PmcXmlMaligngroup();
    }

    /**
     * Create an instance of {@link PmcXmlMspace }
     * 
     */
    public PmcXmlMspace createPmcXmlMspace() {
        return new PmcXmlMspace();
    }

    /**
     * Create an instance of {@link PmcXmlMaction }
     * 
     */
    public PmcXmlMaction createPmcXmlMaction() {
        return new PmcXmlMaction();
    }

    /**
     * Create an instance of {@link PmcXmlMerror }
     * 
     */
    public PmcXmlMerror createPmcXmlMerror() {
        return new PmcXmlMerror();
    }

    /**
     * Create an instance of {@link PmcXmlMstyle }
     * 
     */
    public PmcXmlMstyle createPmcXmlMstyle() {
        return new PmcXmlMstyle();
    }

    /**
     * Create an instance of {@link PmcXmlCn }
     * 
     */
    public PmcXmlCn createPmcXmlCn() {
        return new PmcXmlCn();
    }

    /**
     * Create an instance of {@link PmcXmlCi }
     * 
     */
    public PmcXmlCi createPmcXmlCi() {
        return new PmcXmlCi();
    }

    /**
     * Create an instance of {@link PmcXmlCsymbol }
     * 
     */
    public PmcXmlCsymbol createPmcXmlCsymbol() {
        return new PmcXmlCsymbol();
    }

    /**
     * Create an instance of {@link PmcXmlArithType }
     * 
     */
    public PmcXmlArithType createPmcXmlArithType() {
        return new PmcXmlArithType();
    }

    /**
     * Create an instance of {@link PmcXmlFunctionsType }
     * 
     */
    public PmcXmlFunctionsType createPmcXmlFunctionsType() {
        return new PmcXmlFunctionsType();
    }

    /**
     * Create an instance of {@link PmcXmlDomainofapplication }
     * 
     */
    public PmcXmlDomainofapplication createPmcXmlDomainofapplication() {
        return new PmcXmlDomainofapplication();
    }

    /**
     * Create an instance of {@link PmcXmlSemantics }
     * 
     */
    public PmcXmlSemantics createPmcXmlSemantics() {
        return new PmcXmlSemantics();
    }

    /**
     * Create an instance of {@link PmcXmlElementaryFunctionsType }
     * 
     */
    public PmcXmlElementaryFunctionsType createPmcXmlElementaryFunctionsType() {
        return new PmcXmlElementaryFunctionsType();
    }

    /**
     * Create an instance of {@link PmcXmlLogicType }
     * 
     */
    public PmcXmlLogicType createPmcXmlLogicType() {
        return new PmcXmlLogicType();
    }

    /**
     * Create an instance of {@link PmcXmlConstantType }
     * 
     */
    public PmcXmlConstantType createPmcXmlConstantType() {
        return new PmcXmlConstantType();
    }

    /**
     * Create an instance of {@link PmcXmlSet }
     * 
     */
    public PmcXmlSet createPmcXmlSet() {
        return new PmcXmlSet();
    }

    /**
     * Create an instance of {@link PmcXmlList }
     * 
     */
    public PmcXmlList createPmcXmlList() {
        return new PmcXmlList();
    }

    /**
     * Create an instance of {@link PmcXmlUnion }
     * 
     */
    public PmcXmlUnion createPmcXmlUnion() {
        return new PmcXmlUnion();
    }

    /**
     * Create an instance of {@link PmcXmlIntersect }
     * 
     */
    public PmcXmlIntersect createPmcXmlIntersect() {
        return new PmcXmlIntersect();
    }

    /**
     * Create an instance of {@link PmcXmlIn }
     * 
     */
    public PmcXmlIn createPmcXmlIn() {
        return new PmcXmlIn();
    }

    /**
     * Create an instance of {@link PmcXmlNotin }
     * 
     */
    public PmcXmlNotin createPmcXmlNotin() {
        return new PmcXmlNotin();
    }

    /**
     * Create an instance of {@link PmcXmlSubset }
     * 
     */
    public PmcXmlSubset createPmcXmlSubset() {
        return new PmcXmlSubset();
    }

    /**
     * Create an instance of {@link PmcXmlPrsubset }
     * 
     */
    public PmcXmlPrsubset createPmcXmlPrsubset() {
        return new PmcXmlPrsubset();
    }

    /**
     * Create an instance of {@link PmcXmlNotsubset }
     * 
     */
    public PmcXmlNotsubset createPmcXmlNotsubset() {
        return new PmcXmlNotsubset();
    }

    /**
     * Create an instance of {@link PmcXmlNotprsubset }
     * 
     */
    public PmcXmlNotprsubset createPmcXmlNotprsubset() {
        return new PmcXmlNotprsubset();
    }

    /**
     * Create an instance of {@link PmcXmlSetdiff }
     * 
     */
    public PmcXmlSetdiff createPmcXmlSetdiff() {
        return new PmcXmlSetdiff();
    }

    /**
     * Create an instance of {@link PmcXmlCard }
     * 
     */
    public PmcXmlCard createPmcXmlCard() {
        return new PmcXmlCard();
    }

    /**
     * Create an instance of {@link PmcXmlCartesianproduct }
     * 
     */
    public PmcXmlCartesianproduct createPmcXmlCartesianproduct() {
        return new PmcXmlCartesianproduct();
    }

    /**
     * Create an instance of {@link PmcXmlRelationsType }
     * 
     */
    public PmcXmlRelationsType createPmcXmlRelationsType() {
        return new PmcXmlRelationsType();
    }

    /**
     * Create an instance of {@link PmcXmlLogbase }
     * 
     */
    public PmcXmlLogbase createPmcXmlLogbase() {
        return new PmcXmlLogbase();
    }

    /**
     * Create an instance of {@link PmcXmlDegree }
     * 
     */
    public PmcXmlDegree createPmcXmlDegree() {
        return new PmcXmlDegree();
    }

    /**
     * Create an instance of {@link PmcXmlInt }
     * 
     */
    public PmcXmlInt createPmcXmlInt() {
        return new PmcXmlInt();
    }

    /**
     * Create an instance of {@link PmcXmlDiff }
     * 
     */
    public PmcXmlDiff createPmcXmlDiff() {
        return new PmcXmlDiff();
    }

    /**
     * Create an instance of {@link PmcXmlPartialdiff }
     * 
     */
    public PmcXmlPartialdiff createPmcXmlPartialdiff() {
        return new PmcXmlPartialdiff();
    }

    /**
     * Create an instance of {@link PmcXmlLimit }
     * 
     */
    public PmcXmlLimit createPmcXmlLimit() {
        return new PmcXmlLimit();
    }

    /**
     * Create an instance of {@link PmcXmlLowlimit }
     * 
     */
    public PmcXmlLowlimit createPmcXmlLowlimit() {
        return new PmcXmlLowlimit();
    }

    /**
     * Create an instance of {@link PmcXmlUplimit }
     * 
     */
    public PmcXmlUplimit createPmcXmlUplimit() {
        return new PmcXmlUplimit();
    }

    /**
     * Create an instance of {@link PmcXmlTendsto }
     * 
     */
    public PmcXmlTendsto createPmcXmlTendsto() {
        return new PmcXmlTendsto();
    }

    /**
     * Create an instance of {@link PmcXmlVector }
     * 
     */
    public PmcXmlVector createPmcXmlVector() {
        return new PmcXmlVector();
    }

    /**
     * Create an instance of {@link PmcXmlMatrix }
     * 
     */
    public PmcXmlMatrix createPmcXmlMatrix() {
        return new PmcXmlMatrix();
    }

    /**
     * Create an instance of {@link PmcXmlMatrixrow }
     * 
     */
    public PmcXmlMatrixrow createPmcXmlMatrixrow() {
        return new PmcXmlMatrixrow();
    }

    /**
     * Create an instance of {@link PmcXmlDeterminant }
     * 
     */
    public PmcXmlDeterminant createPmcXmlDeterminant() {
        return new PmcXmlDeterminant();
    }

    /**
     * Create an instance of {@link PmcXmlTranspose }
     * 
     */
    public PmcXmlTranspose createPmcXmlTranspose() {
        return new PmcXmlTranspose();
    }

    /**
     * Create an instance of {@link PmcXmlSelector }
     * 
     */
    public PmcXmlSelector createPmcXmlSelector() {
        return new PmcXmlSelector();
    }

    /**
     * Create an instance of {@link PmcXmlVectorproduct }
     * 
     */
    public PmcXmlVectorproduct createPmcXmlVectorproduct() {
        return new PmcXmlVectorproduct();
    }

    /**
     * Create an instance of {@link PmcXmlScalarproduct }
     * 
     */
    public PmcXmlScalarproduct createPmcXmlScalarproduct() {
        return new PmcXmlScalarproduct();
    }

    /**
     * Create an instance of {@link PmcXmlOuterproduct }
     * 
     */
    public PmcXmlOuterproduct createPmcXmlOuterproduct() {
        return new PmcXmlOuterproduct();
    }

    /**
     * Create an instance of {@link PmcXmlDivergence }
     * 
     */
    public PmcXmlDivergence createPmcXmlDivergence() {
        return new PmcXmlDivergence();
    }

    /**
     * Create an instance of {@link PmcXmlGrad }
     * 
     */
    public PmcXmlGrad createPmcXmlGrad() {
        return new PmcXmlGrad();
    }

    /**
     * Create an instance of {@link PmcXmlCurl }
     * 
     */
    public PmcXmlCurl createPmcXmlCurl() {
        return new PmcXmlCurl();
    }

    /**
     * Create an instance of {@link PmcXmlLaplacian }
     * 
     */
    public PmcXmlLaplacian createPmcXmlLaplacian() {
        return new PmcXmlLaplacian();
    }

    /**
     * Create an instance of {@link PmcXmlMean }
     * 
     */
    public PmcXmlMean createPmcXmlMean() {
        return new PmcXmlMean();
    }

    /**
     * Create an instance of {@link PmcXmlSdev }
     * 
     */
    public PmcXmlSdev createPmcXmlSdev() {
        return new PmcXmlSdev();
    }

    /**
     * Create an instance of {@link PmcXmlVariance }
     * 
     */
    public PmcXmlVariance createPmcXmlVariance() {
        return new PmcXmlVariance();
    }

    /**
     * Create an instance of {@link PmcXmlMedian }
     * 
     */
    public PmcXmlMedian createPmcXmlMedian() {
        return new PmcXmlMedian();
    }

    /**
     * Create an instance of {@link PmcXmlMode }
     * 
     */
    public PmcXmlMode createPmcXmlMode() {
        return new PmcXmlMode();
    }

    /**
     * Create an instance of {@link PmcXmlMoment }
     * 
     */
    public PmcXmlMoment createPmcXmlMoment() {
        return new PmcXmlMoment();
    }

    /**
     * Create an instance of {@link PmcXmlMomentabout }
     * 
     */
    public PmcXmlMomentabout createPmcXmlMomentabout() {
        return new PmcXmlMomentabout();
    }

    /**
     * Create an instance of {@link PmcXmlApply }
     * 
     */
    public PmcXmlApply createPmcXmlApply() {
        return new PmcXmlApply();
    }

    /**
     * Create an instance of {@link PmcXmlInterval }
     * 
     */
    public PmcXmlInterval createPmcXmlInterval() {
        return new PmcXmlInterval();
    }

    /**
     * Create an instance of {@link PmcXmlInverse }
     * 
     */
    public PmcXmlInverse createPmcXmlInverse() {
        return new PmcXmlInverse();
    }

    /**
     * Create an instance of {@link PmcXmlCondition }
     * 
     */
    public PmcXmlCondition createPmcXmlCondition() {
        return new PmcXmlCondition();
    }

    /**
     * Create an instance of {@link PmcXmlDeclare }
     * 
     */
    public PmcXmlDeclare createPmcXmlDeclare() {
        return new PmcXmlDeclare();
    }

    /**
     * Create an instance of {@link PmcXmlLambda }
     * 
     */
    public PmcXmlLambda createPmcXmlLambda() {
        return new PmcXmlLambda();
    }

    /**
     * Create an instance of {@link PmcXmlPiecewise }
     * 
     */
    public PmcXmlPiecewise createPmcXmlPiecewise() {
        return new PmcXmlPiecewise();
    }

    /**
     * Create an instance of {@link PmcXmlPiece }
     * 
     */
    public PmcXmlPiece createPmcXmlPiece() {
        return new PmcXmlPiece();
    }

    /**
     * Create an instance of {@link PmcXmlBvar }
     * 
     */
    public PmcXmlBvar createPmcXmlBvar() {
        return new PmcXmlBvar();
    }

    /**
     * Create an instance of {@link PmcXmlOtherwise }
     * 
     */
    public PmcXmlOtherwise createPmcXmlOtherwise() {
        return new PmcXmlOtherwise();
    }

    /**
     * Create an instance of {@link PmcXmlAnnotation }
     * 
     */
    public PmcXmlAnnotation createPmcXmlAnnotation() {
        return new PmcXmlAnnotation();
    }

    /**
     * Create an instance of {@link PmcXmlAnnotationXml }
     * 
     */
    public PmcXmlAnnotationXml createPmcXmlAnnotationXml() {
        return new PmcXmlAnnotationXml();
    }

    /**
     * Create an instance of {@link PmcXmlSep }
     * 
     */
    public PmcXmlSep createPmcXmlSep() {
        return new PmcXmlSep();
    }

    /**
     * Create an instance of {@link PmcXmlMlabeledtr }
     * 
     */
    public PmcXmlMlabeledtr createPmcXmlMlabeledtr() {
        return new PmcXmlMlabeledtr();
    }

    /**
     * Create an instance of {@link PmcXmlNone }
     * 
     */
    public PmcXmlNone createPmcXmlNone() {
        return new PmcXmlNone();
    }

    /**
     * Create an instance of {@link PmcXmlMprescripts }
     * 
     */
    public PmcXmlMprescripts createPmcXmlMprescripts() {
        return new PmcXmlMprescripts();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlLogicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "xor")
    public JAXBElement<PmcXmlLogicType> createXor(PmcXmlLogicType value) {
        return new JAXBElement<PmcXmlLogicType>(_Xor_QNAME, PmcXmlLogicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "max")
    public JAXBElement<PmcXmlArithType> createMax(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Max_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "min")
    public JAXBElement<PmcXmlArithType> createMin(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Min_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arctan")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArctan(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arctan_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "leq")
    public JAXBElement<PmcXmlRelationsType> createLeq(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Leq_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "divide")
    public JAXBElement<PmcXmlArithType> createDivide(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Divide_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "true")
    public JAXBElement<PmcXmlConstantType> createTrue(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_True_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "product")
    public JAXBElement<PmcXmlArithType> createProduct(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Product_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arcsin")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArcsin(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arcsin_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "csc")
    public JAXBElement<PmcXmlElementaryFunctionsType> createCsc(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Csc_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "sec")
    public JAXBElement<PmcXmlElementaryFunctionsType> createSec(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Sec_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "sin")
    public JAXBElement<PmcXmlElementaryFunctionsType> createSin(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Sin_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "factorial")
    public JAXBElement<PmcXmlArithType> createFactorial(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Factorial_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "primes")
    public JAXBElement<PmcXmlConstantType> createPrimes(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Primes_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "rem")
    public JAXBElement<PmcXmlArithType> createRem(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Rem_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlLogicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "exists")
    public JAXBElement<PmcXmlLogicType> createExists(PmcXmlLogicType value) {
        return new JAXBElement<PmcXmlLogicType>(_Exists_QNAME, PmcXmlLogicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "emptyset")
    public JAXBElement<PmcXmlConstantType> createEmptyset(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Emptyset_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arccosh")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArccosh(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arccosh_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "eq")
    public JAXBElement<PmcXmlRelationsType> createEq(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Eq_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "gcd")
    public JAXBElement<PmcXmlArithType> createGcd(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Gcd_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "imaginaryi")
    public JAXBElement<PmcXmlConstantType> createImaginaryi(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Imaginaryi_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "equivalent")
    public JAXBElement<PmcXmlRelationsType> createEquivalent(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Equivalent_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "ln")
    public JAXBElement<PmcXmlElementaryFunctionsType> createLn(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Ln_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlLogicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "implies")
    public JAXBElement<PmcXmlLogicType> createImplies(PmcXmlLogicType value) {
        return new JAXBElement<PmcXmlLogicType>(_Implies_QNAME, PmcXmlLogicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "imaginary")
    public JAXBElement<PmcXmlArithType> createImaginary(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Imaginary_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "lt")
    public JAXBElement<PmcXmlRelationsType> createLt(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Lt_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "neq")
    public JAXBElement<PmcXmlRelationsType> createNeq(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Neq_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "sum")
    public JAXBElement<PmcXmlArithType> createSum(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Sum_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "infinity")
    public JAXBElement<PmcXmlConstantType> createInfinity(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Infinity_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arcsech")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArcsech(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arcsech_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "approx")
    public JAXBElement<PmcXmlRelationsType> createApprox(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Approx_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "real")
    public JAXBElement<PmcXmlArithType> createReal(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Real_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "ident")
    public JAXBElement<PmcXmlFunctionsType> createIdent(PmcXmlFunctionsType value) {
        return new JAXBElement<PmcXmlFunctionsType>(_Ident_QNAME, PmcXmlFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "times")
    public JAXBElement<PmcXmlArithType> createTimes(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Times_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "domain")
    public JAXBElement<PmcXmlFunctionsType> createDomain(PmcXmlFunctionsType value) {
        return new JAXBElement<PmcXmlFunctionsType>(_Domain_QNAME, PmcXmlFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arccoth")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArccoth(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arccoth_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "csch")
    public JAXBElement<PmcXmlElementaryFunctionsType> createCsch(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Csch_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "minus")
    public JAXBElement<PmcXmlArithType> createMinus(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Minus_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "cosh")
    public JAXBElement<PmcXmlElementaryFunctionsType> createCosh(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Cosh_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "geq")
    public JAXBElement<PmcXmlRelationsType> createGeq(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Geq_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "plus")
    public JAXBElement<PmcXmlArithType> createPlus(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Plus_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlLogicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "or")
    public JAXBElement<PmcXmlLogicType> createOr(PmcXmlLogicType value) {
        return new JAXBElement<PmcXmlLogicType>(_Or_QNAME, PmcXmlLogicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arccsch")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArccsch(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arccsch_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "sech")
    public JAXBElement<PmcXmlElementaryFunctionsType> createSech(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Sech_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arctanh")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArctanh(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arctanh_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "sinh")
    public JAXBElement<PmcXmlElementaryFunctionsType> createSinh(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Sinh_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "image")
    public JAXBElement<PmcXmlFunctionsType> createImage(PmcXmlFunctionsType value) {
        return new JAXBElement<PmcXmlFunctionsType>(_Image_QNAME, PmcXmlFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arccsc")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArccsc(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arccsc_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "factorof")
    public JAXBElement<PmcXmlRelationsType> createFactorof(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Factorof_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "and")
    public JAXBElement<PmcXmlElementaryFunctionsType> createAnd(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_And_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "exponentiale")
    public JAXBElement<PmcXmlConstantType> createExponentiale(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Exponentiale_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "conjugate")
    public JAXBElement<PmcXmlArithType> createConjugate(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Conjugate_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlLogicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "forall")
    public JAXBElement<PmcXmlLogicType> createForall(PmcXmlLogicType value) {
        return new JAXBElement<PmcXmlLogicType>(_Forall_QNAME, PmcXmlLogicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "log")
    public JAXBElement<PmcXmlElementaryFunctionsType> createLog(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Log_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlLogicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "not")
    public JAXBElement<PmcXmlLogicType> createNot(PmcXmlLogicType value) {
        return new JAXBElement<PmcXmlLogicType>(_Not_QNAME, PmcXmlLogicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "exp")
    public JAXBElement<PmcXmlElementaryFunctionsType> createExp(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Exp_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "floor")
    public JAXBElement<PmcXmlArithType> createFloor(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Floor_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "ceiling")
    public JAXBElement<PmcXmlArithType> createCeiling(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Ceiling_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "rationals")
    public JAXBElement<PmcXmlConstantType> createRationals(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Rationals_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlRelationsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "gt")
    public JAXBElement<PmcXmlRelationsType> createGt(PmcXmlRelationsType value) {
        return new JAXBElement<PmcXmlRelationsType>(_Gt_QNAME, PmcXmlRelationsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "tan")
    public JAXBElement<PmcXmlElementaryFunctionsType> createTan(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Tan_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "pi")
    public JAXBElement<PmcXmlConstantType> createPi(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Pi_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "coth")
    public JAXBElement<PmcXmlElementaryFunctionsType> createCoth(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Coth_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "integers")
    public JAXBElement<PmcXmlConstantType> createIntegers(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Integers_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "complexes")
    public JAXBElement<PmcXmlConstantType> createComplexes(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Complexes_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arcsinh")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArcsinh(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arcsinh_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "quotient")
    public JAXBElement<PmcXmlArithType> createQuotient(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Quotient_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arccot")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArccot(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arccot_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arccos")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArccos(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arccos_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "cos")
    public JAXBElement<PmcXmlElementaryFunctionsType> createCos(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Cos_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "root")
    public JAXBElement<PmcXmlArithType> createRoot(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Root_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "cot")
    public JAXBElement<PmcXmlElementaryFunctionsType> createCot(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Cot_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "reals")
    public JAXBElement<PmcXmlConstantType> createReals(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Reals_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "naturalnumbers")
    public JAXBElement<PmcXmlConstantType> createNaturalnumbers(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Naturalnumbers_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "lcm")
    public JAXBElement<PmcXmlArithType> createLcm(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Lcm_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "abs")
    public JAXBElement<PmcXmlArithType> createAbs(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Abs_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "tanh")
    public JAXBElement<PmcXmlElementaryFunctionsType> createTanh(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Tanh_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "notanumber")
    public JAXBElement<PmcXmlConstantType> createNotanumber(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Notanumber_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arg")
    public JAXBElement<PmcXmlArithType> createArg(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Arg_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlElementaryFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "arcsec")
    public JAXBElement<PmcXmlElementaryFunctionsType> createArcsec(PmcXmlElementaryFunctionsType value) {
        return new JAXBElement<PmcXmlElementaryFunctionsType>(_Arcsec_QNAME, PmcXmlElementaryFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "codomain")
    public JAXBElement<PmcXmlFunctionsType> createCodomain(PmcXmlFunctionsType value) {
        return new JAXBElement<PmcXmlFunctionsType>(_Codomain_QNAME, PmcXmlFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlFunctionsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "compose")
    public JAXBElement<PmcXmlFunctionsType> createCompose(PmcXmlFunctionsType value) {
        return new JAXBElement<PmcXmlFunctionsType>(_Compose_QNAME, PmcXmlFunctionsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlArithType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "power")
    public JAXBElement<PmcXmlArithType> createPower(PmcXmlArithType value) {
        return new JAXBElement<PmcXmlArithType>(_Power_QNAME, PmcXmlArithType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "false")
    public JAXBElement<PmcXmlConstantType> createFalse(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_False_QNAME, PmcXmlConstantType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PmcXmlConstantType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1998/Math/MathML", name = "eulergamma")
    public JAXBElement<PmcXmlConstantType> createEulergamma(PmcXmlConstantType value) {
        return new JAXBElement<PmcXmlConstantType>(_Eulergamma_QNAME, PmcXmlConstantType.class, null, value);
    }

}
