//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.isi.bmkeg.lapdf.pmcXml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Surname_QNAME = new QName("", "surname");
    private final static QName _GivenNames_QNAME = new QName("", "given-names");
    private final static QName _Etal_QNAME = new QName("", "etal");
    private final static QName _MetaName_QNAME = new QName("", "meta-name");
    private final static QName _PublisherName_QNAME = new QName("", "publisher-name");
    private final static QName _Prefix_QNAME = new QName("", "prefix");
    private final static QName _IssuePart_QNAME = new QName("", "issue-part");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.isi.bmkeg.lapdf.pmcXml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PmcXmlOnBehalfOf }
     * 
     */
    public PmcXmlOnBehalfOf createPmcXmlOnBehalfOf() {
        return new PmcXmlOnBehalfOf();
    }

    /**
     * Create an instance of {@link PmcXmlBold }
     * 
     */
    public PmcXmlBold createPmcXmlBold() {
        return new PmcXmlBold();
    }

    /**
     * Create an instance of {@link PmcXmlEmail }
     * 
     */
    public PmcXmlEmail createPmcXmlEmail() {
        return new PmcXmlEmail();
    }

    /**
     * Create an instance of {@link PmcXmlExtLink }
     * 
     */
    public PmcXmlExtLink createPmcXmlExtLink() {
        return new PmcXmlExtLink();
    }

    /**
     * Create an instance of {@link PmcXmlItalic }
     * 
     */
    public PmcXmlItalic createPmcXmlItalic() {
        return new PmcXmlItalic();
    }

    /**
     * Create an instance of {@link PmcXmlUri }
     * 
     */
    public PmcXmlUri createPmcXmlUri() {
        return new PmcXmlUri();
    }

    /**
     * Create an instance of {@link PmcXmlInlineSupplementaryMaterial }
     * 
     */
    public PmcXmlInlineSupplementaryMaterial createPmcXmlInlineSupplementaryMaterial() {
        return new PmcXmlInlineSupplementaryMaterial();
    }

    /**
     * Create an instance of {@link PmcXmlAltText }
     * 
     */
    public PmcXmlAltText createPmcXmlAltText() {
        return new PmcXmlAltText();
    }

    /**
     * Create an instance of {@link PmcXmlLongDesc }
     * 
     */
    public PmcXmlLongDesc createPmcXmlLongDesc() {
        return new PmcXmlLongDesc();
    }

    /**
     * Create an instance of {@link PmcXmlMonospace }
     * 
     */
    public PmcXmlMonospace createPmcXmlMonospace() {
        return new PmcXmlMonospace();
    }

    /**
     * Create an instance of {@link PmcXmlRelatedArticle }
     * 
     */
    public PmcXmlRelatedArticle createPmcXmlRelatedArticle() {
        return new PmcXmlRelatedArticle();
    }

    /**
     * Create an instance of {@link PmcXmlOverline }
     * 
     */
    public PmcXmlOverline createPmcXmlOverline() {
        return new PmcXmlOverline();
    }

    /**
     * Create an instance of {@link PmcXmlRelatedObject }
     * 
     */
    public PmcXmlRelatedObject createPmcXmlRelatedObject() {
        return new PmcXmlRelatedObject();
    }

    /**
     * Create an instance of {@link PmcXmlRoman }
     * 
     */
    public PmcXmlRoman createPmcXmlRoman() {
        return new PmcXmlRoman();
    }

    /**
     * Create an instance of {@link PmcXmlSansSerif }
     * 
     */
    public PmcXmlSansSerif createPmcXmlSansSerif() {
        return new PmcXmlSansSerif();
    }

    /**
     * Create an instance of {@link PmcXmlSc }
     * 
     */
    public PmcXmlSc createPmcXmlSc() {
        return new PmcXmlSc();
    }

    /**
     * Create an instance of {@link PmcXmlStrike }
     * 
     */
    public PmcXmlStrike createPmcXmlStrike() {
        return new PmcXmlStrike();
    }

    /**
     * Create an instance of {@link PmcXmlUnderline }
     * 
     */
    public PmcXmlUnderline createPmcXmlUnderline() {
        return new PmcXmlUnderline();
    }

    /**
     * Create an instance of {@link PmcXmlAlternatives }
     * 
     */
    public PmcXmlAlternatives createPmcXmlAlternatives() {
        return new PmcXmlAlternatives();
    }

    /**
     * Create an instance of {@link PmcXmlArray }
     * 
     */
    public PmcXmlArray createPmcXmlArray() {
        return new PmcXmlArray();
    }

    /**
     * Create an instance of {@link PmcXmlTbody }
     * 
     */
    public PmcXmlTbody createPmcXmlTbody() {
        return new PmcXmlTbody();
    }

    /**
     * Create an instance of {@link PmcXmlTr }
     * 
     */
    public PmcXmlTr createPmcXmlTr() {
        return new PmcXmlTr();
    }

    /**
     * Create an instance of {@link PmcXmlTh }
     * 
     */
    public PmcXmlTh createPmcXmlTh() {
        return new PmcXmlTh();
    }

    /**
     * Create an instance of {@link PmcXmlHr }
     * 
     */
    public PmcXmlHr createPmcXmlHr() {
        return new PmcXmlHr();
    }

    /**
     * Create an instance of {@link PmcXmlDispFormula }
     * 
     */
    public PmcXmlDispFormula createPmcXmlDispFormula() {
        return new PmcXmlDispFormula();
    }

    /**
     * Create an instance of {@link PmcXmlBreak }
     * 
     */
    public PmcXmlBreak createPmcXmlBreak() {
        return new PmcXmlBreak();
    }

    /**
     * Create an instance of {@link PmcXmlInlineGraphic }
     * 
     */
    public PmcXmlInlineGraphic createPmcXmlInlineGraphic() {
        return new PmcXmlInlineGraphic();
    }

    /**
     * Create an instance of {@link PmcXmlPrivateChar }
     * 
     */
    public PmcXmlPrivateChar createPmcXmlPrivateChar() {
        return new PmcXmlPrivateChar();
    }

    /**
     * Create an instance of {@link PmcXmlGlyphRef }
     * 
     */
    public PmcXmlGlyphRef createPmcXmlGlyphRef() {
        return new PmcXmlGlyphRef();
    }

    /**
     * Create an instance of {@link PmcXmlGlyphData }
     * 
     */
    public PmcXmlGlyphData createPmcXmlGlyphData() {
        return new PmcXmlGlyphData();
    }

    /**
     * Create an instance of {@link PmcXmlChemStruct }
     * 
     */
    public PmcXmlChemStruct createPmcXmlChemStruct() {
        return new PmcXmlChemStruct();
    }

    /**
     * Create an instance of {@link PmcXmlLabel }
     * 
     */
    public PmcXmlLabel createPmcXmlLabel() {
        return new PmcXmlLabel();
    }

    /**
     * Create an instance of {@link PmcXmlInlineFormula }
     * 
     */
    public PmcXmlInlineFormula createPmcXmlInlineFormula() {
        return new PmcXmlInlineFormula();
    }

    /**
     * Create an instance of {@link PmcXmlTexMath }
     * 
     */
    public PmcXmlTexMath createPmcXmlTexMath() {
        return new PmcXmlTexMath();
    }

    /**
     * Create an instance of {@link PmcXmlNamedContent }
     * 
     */
    public PmcXmlNamedContent createPmcXmlNamedContent() {
        return new PmcXmlNamedContent();
    }

    /**
     * Create an instance of {@link PmcXmlAddress }
     * 
     */
    public PmcXmlAddress createPmcXmlAddress() {
        return new PmcXmlAddress();
    }

    /**
     * Create an instance of {@link PmcXmlAddrLine }
     * 
     */
    public PmcXmlAddrLine createPmcXmlAddrLine() {
        return new PmcXmlAddrLine();
    }

    /**
     * Create an instance of {@link PmcXmlAbbrev }
     * 
     */
    public PmcXmlAbbrev createPmcXmlAbbrev() {
        return new PmcXmlAbbrev();
    }

    /**
     * Create an instance of {@link PmcXmlDef }
     * 
     */
    public PmcXmlDef createPmcXmlDef() {
        return new PmcXmlDef();
    }

    /**
     * Create an instance of {@link PmcXmlP }
     * 
     */
    public PmcXmlP createPmcXmlP() {
        return new PmcXmlP();
    }

    /**
     * Create an instance of {@link PmcXmlBoxedText }
     * 
     */
    public PmcXmlBoxedText createPmcXmlBoxedText() {
        return new PmcXmlBoxedText();
    }

    /**
     * Create an instance of {@link PmcXmlObjectId }
     * 
     */
    public PmcXmlObjectId createPmcXmlObjectId() {
        return new PmcXmlObjectId();
    }

    /**
     * Create an instance of {@link PmcXmlSecMeta }
     * 
     */
    public PmcXmlSecMeta createPmcXmlSecMeta() {
        return new PmcXmlSecMeta();
    }

    /**
     * Create an instance of {@link PmcXmlContribGroup }
     * 
     */
    public PmcXmlContribGroup createPmcXmlContribGroup() {
        return new PmcXmlContribGroup();
    }

    /**
     * Create an instance of {@link PmcXmlContrib }
     * 
     */
    public PmcXmlContrib createPmcXmlContrib() {
        return new PmcXmlContrib();
    }

    /**
     * Create an instance of {@link PmcXmlAnonymous }
     * 
     */
    public PmcXmlAnonymous createPmcXmlAnonymous() {
        return new PmcXmlAnonymous();
    }

    /**
     * Create an instance of {@link PmcXmlCollab }
     * 
     */
    public PmcXmlCollab createPmcXmlCollab() {
        return new PmcXmlCollab();
    }

    /**
     * Create an instance of {@link PmcXmlMilestoneEnd }
     * 
     */
    public PmcXmlMilestoneEnd createPmcXmlMilestoneEnd() {
        return new PmcXmlMilestoneEnd();
    }

    /**
     * Create an instance of {@link PmcXmlMilestoneStart }
     * 
     */
    public PmcXmlMilestoneStart createPmcXmlMilestoneStart() {
        return new PmcXmlMilestoneStart();
    }

    /**
     * Create an instance of {@link PmcXmlStyledContent }
     * 
     */
    public PmcXmlStyledContent createPmcXmlStyledContent() {
        return new PmcXmlStyledContent();
    }

    /**
     * Create an instance of {@link PmcXmlChemStructWrap }
     * 
     */
    public PmcXmlChemStructWrap createPmcXmlChemStructWrap() {
        return new PmcXmlChemStructWrap();
    }

    /**
     * Create an instance of {@link PmcXmlCaption }
     * 
     */
    public PmcXmlCaption createPmcXmlCaption() {
        return new PmcXmlCaption();
    }

    /**
     * Create an instance of {@link PmcXmlTitle }
     * 
     */
    public PmcXmlTitle createPmcXmlTitle() {
        return new PmcXmlTitle();
    }

    /**
     * Create an instance of {@link PmcXmlFn }
     * 
     */
    public PmcXmlFn createPmcXmlFn() {
        return new PmcXmlFn();
    }

    /**
     * Create an instance of {@link PmcXmlTarget }
     * 
     */
    public PmcXmlTarget createPmcXmlTarget() {
        return new PmcXmlTarget();
    }

    /**
     * Create an instance of {@link PmcXmlSub }
     * 
     */
    public PmcXmlSub createPmcXmlSub() {
        return new PmcXmlSub();
    }

    /**
     * Create an instance of {@link PmcXmlXref }
     * 
     */
    public PmcXmlXref createPmcXmlXref() {
        return new PmcXmlXref();
    }

    /**
     * Create an instance of {@link PmcXmlSup }
     * 
     */
    public PmcXmlSup createPmcXmlSup() {
        return new PmcXmlSup();
    }

    /**
     * Create an instance of {@link PmcXmlElementCitation }
     * 
     */
    public PmcXmlElementCitation createPmcXmlElementCitation() {
        return new PmcXmlElementCitation();
    }

    /**
     * Create an instance of {@link PmcXmlAnnotation }
     * 
     */
    public PmcXmlAnnotation createPmcXmlAnnotation() {
        return new PmcXmlAnnotation();
    }

    /**
     * Create an instance of {@link PmcXmlArticleTitle }
     * 
     */
    public PmcXmlArticleTitle createPmcXmlArticleTitle() {
        return new PmcXmlArticleTitle();
    }

    /**
     * Create an instance of {@link PmcXmlChapterTitle }
     * 
     */
    public PmcXmlChapterTitle createPmcXmlChapterTitle() {
        return new PmcXmlChapterTitle();
    }

    /**
     * Create an instance of {@link PmcXmlComment }
     * 
     */
    public PmcXmlComment createPmcXmlComment() {
        return new PmcXmlComment();
    }

    /**
     * Create an instance of {@link PmcXmlConfDate }
     * 
     */
    public PmcXmlConfDate createPmcXmlConfDate() {
        return new PmcXmlConfDate();
    }

    /**
     * Create an instance of {@link PmcXmlConfLoc }
     * 
     */
    public PmcXmlConfLoc createPmcXmlConfLoc() {
        return new PmcXmlConfLoc();
    }

    /**
     * Create an instance of {@link PmcXmlConfName }
     * 
     */
    public PmcXmlConfName createPmcXmlConfName() {
        return new PmcXmlConfName();
    }

    /**
     * Create an instance of {@link PmcXmlConfSponsor }
     * 
     */
    public PmcXmlConfSponsor createPmcXmlConfSponsor() {
        return new PmcXmlConfSponsor();
    }

    /**
     * Create an instance of {@link PmcXmlDate }
     * 
     */
    public PmcXmlDate createPmcXmlDate() {
        return new PmcXmlDate();
    }

    /**
     * Create an instance of {@link PmcXmlSeason }
     * 
     */
    public PmcXmlSeason createPmcXmlSeason() {
        return new PmcXmlSeason();
    }

    /**
     * Create an instance of {@link PmcXmlDay }
     * 
     */
    public PmcXmlDay createPmcXmlDay() {
        return new PmcXmlDay();
    }

    /**
     * Create an instance of {@link PmcXmlMonth }
     * 
     */
    public PmcXmlMonth createPmcXmlMonth() {
        return new PmcXmlMonth();
    }

    /**
     * Create an instance of {@link PmcXmlYear }
     * 
     */
    public PmcXmlYear createPmcXmlYear() {
        return new PmcXmlYear();
    }

    /**
     * Create an instance of {@link PmcXmlDateInCitation }
     * 
     */
    public PmcXmlDateInCitation createPmcXmlDateInCitation() {
        return new PmcXmlDateInCitation();
    }

    /**
     * Create an instance of {@link PmcXmlEdition }
     * 
     */
    public PmcXmlEdition createPmcXmlEdition() {
        return new PmcXmlEdition();
    }

    /**
     * Create an instance of {@link PmcXmlElocationId }
     * 
     */
    public PmcXmlElocationId createPmcXmlElocationId() {
        return new PmcXmlElocationId();
    }

    /**
     * Create an instance of {@link PmcXmlFpage }
     * 
     */
    public PmcXmlFpage createPmcXmlFpage() {
        return new PmcXmlFpage();
    }

    /**
     * Create an instance of {@link PmcXmlGov }
     * 
     */
    public PmcXmlGov createPmcXmlGov() {
        return new PmcXmlGov();
    }

    /**
     * Create an instance of {@link PmcXmlInstitution }
     * 
     */
    public PmcXmlInstitution createPmcXmlInstitution() {
        return new PmcXmlInstitution();
    }

    /**
     * Create an instance of {@link PmcXmlIsbn }
     * 
     */
    public PmcXmlIsbn createPmcXmlIsbn() {
        return new PmcXmlIsbn();
    }

    /**
     * Create an instance of {@link PmcXmlIssn }
     * 
     */
    public PmcXmlIssn createPmcXmlIssn() {
        return new PmcXmlIssn();
    }

    /**
     * Create an instance of {@link PmcXmlIssue }
     * 
     */
    public PmcXmlIssue createPmcXmlIssue() {
        return new PmcXmlIssue();
    }

    /**
     * Create an instance of {@link PmcXmlIssueId }
     * 
     */
    public PmcXmlIssueId createPmcXmlIssueId() {
        return new PmcXmlIssueId();
    }

    /**
     * Create an instance of {@link PmcXmlIssueTitle }
     * 
     */
    public PmcXmlIssueTitle createPmcXmlIssueTitle() {
        return new PmcXmlIssueTitle();
    }

    /**
     * Create an instance of {@link PmcXmlLpage }
     * 
     */
    public PmcXmlLpage createPmcXmlLpage() {
        return new PmcXmlLpage();
    }

    /**
     * Create an instance of {@link PmcXmlName }
     * 
     */
    public PmcXmlName createPmcXmlName() {
        return new PmcXmlName();
    }

    /**
     * Create an instance of {@link PmcXmlSuffix }
     * 
     */
    public PmcXmlSuffix createPmcXmlSuffix() {
        return new PmcXmlSuffix();
    }

    /**
     * Create an instance of {@link PmcXmlPageRange }
     * 
     */
    public PmcXmlPageRange createPmcXmlPageRange() {
        return new PmcXmlPageRange();
    }

    /**
     * Create an instance of {@link PmcXmlPartTitle }
     * 
     */
    public PmcXmlPartTitle createPmcXmlPartTitle() {
        return new PmcXmlPartTitle();
    }

    /**
     * Create an instance of {@link PmcXmlPatent }
     * 
     */
    public PmcXmlPatent createPmcXmlPatent() {
        return new PmcXmlPatent();
    }

    /**
     * Create an instance of {@link PmcXmlPersonGroup }
     * 
     */
    public PmcXmlPersonGroup createPmcXmlPersonGroup() {
        return new PmcXmlPersonGroup();
    }

    /**
     * Create an instance of {@link PmcXmlAff }
     * 
     */
    public PmcXmlAff createPmcXmlAff() {
        return new PmcXmlAff();
    }

    /**
     * Create an instance of {@link PmcXmlCountry }
     * 
     */
    public PmcXmlCountry createPmcXmlCountry() {
        return new PmcXmlCountry();
    }

    /**
     * Create an instance of {@link PmcXmlFax }
     * 
     */
    public PmcXmlFax createPmcXmlFax() {
        return new PmcXmlFax();
    }

    /**
     * Create an instance of {@link PmcXmlPhone }
     * 
     */
    public PmcXmlPhone createPmcXmlPhone() {
        return new PmcXmlPhone();
    }

    /**
     * Create an instance of {@link PmcXmlStringName }
     * 
     */
    public PmcXmlStringName createPmcXmlStringName() {
        return new PmcXmlStringName();
    }

    /**
     * Create an instance of {@link PmcXmlDegrees }
     * 
     */
    public PmcXmlDegrees createPmcXmlDegrees() {
        return new PmcXmlDegrees();
    }

    /**
     * Create an instance of {@link PmcXmlPubId }
     * 
     */
    public PmcXmlPubId createPmcXmlPubId() {
        return new PmcXmlPubId();
    }

    /**
     * Create an instance of {@link PmcXmlPublisherLoc }
     * 
     */
    public PmcXmlPublisherLoc createPmcXmlPublisherLoc() {
        return new PmcXmlPublisherLoc();
    }

    /**
     * Create an instance of {@link PmcXmlRole }
     * 
     */
    public PmcXmlRole createPmcXmlRole() {
        return new PmcXmlRole();
    }

    /**
     * Create an instance of {@link PmcXmlSeries }
     * 
     */
    public PmcXmlSeries createPmcXmlSeries() {
        return new PmcXmlSeries();
    }

    /**
     * Create an instance of {@link PmcXmlSize }
     * 
     */
    public PmcXmlSize createPmcXmlSize() {
        return new PmcXmlSize();
    }

    /**
     * Create an instance of {@link PmcXmlSource }
     * 
     */
    public PmcXmlSource createPmcXmlSource() {
        return new PmcXmlSource();
    }

    /**
     * Create an instance of {@link PmcXmlStd }
     * 
     */
    public PmcXmlStd createPmcXmlStd() {
        return new PmcXmlStd();
    }

    /**
     * Create an instance of {@link PmcXmlSupplement }
     * 
     */
    public PmcXmlSupplement createPmcXmlSupplement() {
        return new PmcXmlSupplement();
    }

    /**
     * Create an instance of {@link PmcXmlTransSource }
     * 
     */
    public PmcXmlTransSource createPmcXmlTransSource() {
        return new PmcXmlTransSource();
    }

    /**
     * Create an instance of {@link PmcXmlTransTitle }
     * 
     */
    public PmcXmlTransTitle createPmcXmlTransTitle() {
        return new PmcXmlTransTitle();
    }

    /**
     * Create an instance of {@link PmcXmlVolume }
     * 
     */
    public PmcXmlVolume createPmcXmlVolume() {
        return new PmcXmlVolume();
    }

    /**
     * Create an instance of {@link PmcXmlVolumeId }
     * 
     */
    public PmcXmlVolumeId createPmcXmlVolumeId() {
        return new PmcXmlVolumeId();
    }

    /**
     * Create an instance of {@link PmcXmlVolumeSeries }
     * 
     */
    public PmcXmlVolumeSeries createPmcXmlVolumeSeries() {
        return new PmcXmlVolumeSeries();
    }

    /**
     * Create an instance of {@link PmcXmlMixedCitation }
     * 
     */
    public PmcXmlMixedCitation createPmcXmlMixedCitation() {
        return new PmcXmlMixedCitation();
    }

    /**
     * Create an instance of {@link PmcXmlNlmCitation }
     * 
     */
    public PmcXmlNlmCitation createPmcXmlNlmCitation() {
        return new PmcXmlNlmCitation();
    }

    /**
     * Create an instance of {@link PmcXmlTimeStamp }
     * 
     */
    public PmcXmlTimeStamp createPmcXmlTimeStamp() {
        return new PmcXmlTimeStamp();
    }

    /**
     * Create an instance of {@link PmcXmlAccessDate }
     * 
     */
    public PmcXmlAccessDate createPmcXmlAccessDate() {
        return new PmcXmlAccessDate();
    }

    /**
     * Create an instance of {@link PmcXmlPageCount }
     * 
     */
    public PmcXmlPageCount createPmcXmlPageCount() {
        return new PmcXmlPageCount();
    }

    /**
     * Create an instance of {@link PmcXmlGraphic }
     * 
     */
    public PmcXmlGraphic createPmcXmlGraphic() {
        return new PmcXmlGraphic();
    }

    /**
     * Create an instance of {@link PmcXmlAttrib }
     * 
     */
    public PmcXmlAttrib createPmcXmlAttrib() {
        return new PmcXmlAttrib();
    }

    /**
     * Create an instance of {@link PmcXmlPermissions }
     * 
     */
    public PmcXmlPermissions createPmcXmlPermissions() {
        return new PmcXmlPermissions();
    }

    /**
     * Create an instance of {@link PmcXmlCopyrightStatement }
     * 
     */
    public PmcXmlCopyrightStatement createPmcXmlCopyrightStatement() {
        return new PmcXmlCopyrightStatement();
    }

    /**
     * Create an instance of {@link PmcXmlCopyrightYear }
     * 
     */
    public PmcXmlCopyrightYear createPmcXmlCopyrightYear() {
        return new PmcXmlCopyrightYear();
    }

    /**
     * Create an instance of {@link PmcXmlCopyrightHolder }
     * 
     */
    public PmcXmlCopyrightHolder createPmcXmlCopyrightHolder() {
        return new PmcXmlCopyrightHolder();
    }

    /**
     * Create an instance of {@link PmcXmlLicense }
     * 
     */
    public PmcXmlLicense createPmcXmlLicense() {
        return new PmcXmlLicense();
    }

    /**
     * Create an instance of {@link PmcXmlLicenseP }
     * 
     */
    public PmcXmlLicenseP createPmcXmlLicenseP() {
        return new PmcXmlLicenseP();
    }

    /**
     * Create an instance of {@link PmcXmlFig }
     * 
     */
    public PmcXmlFig createPmcXmlFig() {
        return new PmcXmlFig();
    }

    /**
     * Create an instance of {@link PmcXmlDispFormulaGroup }
     * 
     */
    public PmcXmlDispFormulaGroup createPmcXmlDispFormulaGroup() {
        return new PmcXmlDispFormulaGroup();
    }

    /**
     * Create an instance of {@link PmcXmlDispQuote }
     * 
     */
    public PmcXmlDispQuote createPmcXmlDispQuote() {
        return new PmcXmlDispQuote();
    }

    /**
     * Create an instance of {@link PmcXmlFigGroup }
     * 
     */
    public PmcXmlFigGroup createPmcXmlFigGroup() {
        return new PmcXmlFigGroup();
    }

    /**
     * Create an instance of {@link PmcXmlMedia }
     * 
     */
    public PmcXmlMedia createPmcXmlMedia() {
        return new PmcXmlMedia();
    }

    /**
     * Create an instance of {@link PmcXmlPreformat }
     * 
     */
    public PmcXmlPreformat createPmcXmlPreformat() {
        return new PmcXmlPreformat();
    }

    /**
     * Create an instance of {@link PmcXmlSupplementaryMaterial }
     * 
     */
    public PmcXmlSupplementaryMaterial createPmcXmlSupplementaryMaterial() {
        return new PmcXmlSupplementaryMaterial();
    }

    /**
     * Create an instance of {@link PmcXmlSpeech }
     * 
     */
    public PmcXmlSpeech createPmcXmlSpeech() {
        return new PmcXmlSpeech();
    }

    /**
     * Create an instance of {@link PmcXmlSpeaker }
     * 
     */
    public PmcXmlSpeaker createPmcXmlSpeaker() {
        return new PmcXmlSpeaker();
    }

    /**
     * Create an instance of {@link PmcXmlStatement }
     * 
     */
    public PmcXmlStatement createPmcXmlStatement() {
        return new PmcXmlStatement();
    }

    /**
     * Create an instance of {@link PmcXmlVerseGroup }
     * 
     */
    public PmcXmlVerseGroup createPmcXmlVerseGroup() {
        return new PmcXmlVerseGroup();
    }

    /**
     * Create an instance of {@link PmcXmlSubtitle }
     * 
     */
    public PmcXmlSubtitle createPmcXmlSubtitle() {
        return new PmcXmlSubtitle();
    }

    /**
     * Create an instance of {@link PmcXmlVerseLine }
     * 
     */
    public PmcXmlVerseLine createPmcXmlVerseLine() {
        return new PmcXmlVerseLine();
    }

    /**
     * Create an instance of {@link PmcXmlTableWrap }
     * 
     */
    public PmcXmlTableWrap createPmcXmlTableWrap() {
        return new PmcXmlTableWrap();
    }

    /**
     * Create an instance of {@link PmcXmlDefList }
     * 
     */
    public PmcXmlDefList createPmcXmlDefList() {
        return new PmcXmlDefList();
    }

    /**
     * Create an instance of {@link PmcXmlTermHead }
     * 
     */
    public PmcXmlTermHead createPmcXmlTermHead() {
        return new PmcXmlTermHead();
    }

    /**
     * Create an instance of {@link PmcXmlDefHead }
     * 
     */
    public PmcXmlDefHead createPmcXmlDefHead() {
        return new PmcXmlDefHead();
    }

    /**
     * Create an instance of {@link PmcXmlDefItem }
     * 
     */
    public PmcXmlDefItem createPmcXmlDefItem() {
        return new PmcXmlDefItem();
    }

    /**
     * Create an instance of {@link PmcXmlTerm }
     * 
     */
    public PmcXmlTerm createPmcXmlTerm() {
        return new PmcXmlTerm();
    }

    /**
     * Create an instance of {@link PmcXmlList }
     * 
     */
    public PmcXmlList createPmcXmlList() {
        return new PmcXmlList();
    }

    /**
     * Create an instance of {@link PmcXmlListItem }
     * 
     */
    public PmcXmlListItem createPmcXmlListItem() {
        return new PmcXmlListItem();
    }

    /**
     * Create an instance of {@link PmcXmlTable }
     * 
     */
    public PmcXmlTable createPmcXmlTable() {
        return new PmcXmlTable();
    }

    /**
     * Create an instance of {@link PmcXmlColgroup }
     * 
     */
    public PmcXmlColgroup createPmcXmlColgroup() {
        return new PmcXmlColgroup();
    }

    /**
     * Create an instance of {@link PmcXmlCol }
     * 
     */
    public PmcXmlCol createPmcXmlCol() {
        return new PmcXmlCol();
    }

    /**
     * Create an instance of {@link PmcXmlThead }
     * 
     */
    public PmcXmlThead createPmcXmlThead() {
        return new PmcXmlThead();
    }

    /**
     * Create an instance of {@link PmcXmlTfoot }
     * 
     */
    public PmcXmlTfoot createPmcXmlTfoot() {
        return new PmcXmlTfoot();
    }

    /**
     * Create an instance of {@link PmcXmlTableWrapFoot }
     * 
     */
    public PmcXmlTableWrapFoot createPmcXmlTableWrapFoot() {
        return new PmcXmlTableWrapFoot();
    }

    /**
     * Create an instance of {@link PmcXmlFnGroup }
     * 
     */
    public PmcXmlFnGroup createPmcXmlFnGroup() {
        return new PmcXmlFnGroup();
    }

    /**
     * Create an instance of {@link PmcXmlTableWrapGroup }
     * 
     */
    public PmcXmlTableWrapGroup createPmcXmlTableWrapGroup() {
        return new PmcXmlTableWrapGroup();
    }

    /**
     * Create an instance of {@link PmcXmlAwardId }
     * 
     */
    public PmcXmlAwardId createPmcXmlAwardId() {
        return new PmcXmlAwardId();
    }

    /**
     * Create an instance of {@link PmcXmlFundingSource }
     * 
     */
    public PmcXmlFundingSource createPmcXmlFundingSource() {
        return new PmcXmlFundingSource();
    }

    /**
     * Create an instance of {@link PmcXmlOpenAccess }
     * 
     */
    public PmcXmlOpenAccess createPmcXmlOpenAccess() {
        return new PmcXmlOpenAccess();
    }

    /**
     * Create an instance of {@link PmcXmlPrice }
     * 
     */
    public PmcXmlPrice createPmcXmlPrice() {
        return new PmcXmlPrice();
    }

    /**
     * Create an instance of {@link PmcXmlTextualForm }
     * 
     */
    public PmcXmlTextualForm createPmcXmlTextualForm() {
        return new PmcXmlTextualForm();
    }

    /**
     * Create an instance of {@link PmcXmlAuthorComment }
     * 
     */
    public PmcXmlAuthorComment createPmcXmlAuthorComment() {
        return new PmcXmlAuthorComment();
    }

    /**
     * Create an instance of {@link PmcXmlBio }
     * 
     */
    public PmcXmlBio createPmcXmlBio() {
        return new PmcXmlBio();
    }

    /**
     * Create an instance of {@link PmcXmlSec }
     * 
     */
    public PmcXmlSec createPmcXmlSec() {
        return new PmcXmlSec();
    }

    /**
     * Create an instance of {@link PmcXmlGlossary }
     * 
     */
    public PmcXmlGlossary createPmcXmlGlossary() {
        return new PmcXmlGlossary();
    }

    /**
     * Create an instance of {@link PmcXmlRefList }
     * 
     */
    public PmcXmlRefList createPmcXmlRefList() {
        return new PmcXmlRefList();
    }

    /**
     * Create an instance of {@link PmcXmlRef }
     * 
     */
    public PmcXmlRef createPmcXmlRef() {
        return new PmcXmlRef();
    }

    /**
     * Create an instance of {@link PmcXmlNote }
     * 
     */
    public PmcXmlNote createPmcXmlNote() {
        return new PmcXmlNote();
    }

    /**
     * Create an instance of {@link PmcXmlProduct }
     * 
     */
    public PmcXmlProduct createPmcXmlProduct() {
        return new PmcXmlProduct();
    }

    /**
     * Create an instance of {@link PmcXmlKwdGroup }
     * 
     */
    public PmcXmlKwdGroup createPmcXmlKwdGroup() {
        return new PmcXmlKwdGroup();
    }

    /**
     * Create an instance of {@link PmcXmlKwd }
     * 
     */
    public PmcXmlKwd createPmcXmlKwd() {
        return new PmcXmlKwd();
    }

    /**
     * Create an instance of {@link PmcXmlCompoundKwd }
     * 
     */
    public PmcXmlCompoundKwd createPmcXmlCompoundKwd() {
        return new PmcXmlCompoundKwd();
    }

    /**
     * Create an instance of {@link PmcXmlCompoundKwdPart }
     * 
     */
    public PmcXmlCompoundKwdPart createPmcXmlCompoundKwdPart() {
        return new PmcXmlCompoundKwdPart();
    }

    /**
     * Create an instance of {@link PmcXmlTd }
     * 
     */
    public PmcXmlTd createPmcXmlTd() {
        return new PmcXmlTd();
    }

    /**
     * Create an instance of {@link PmcXmlJournalId }
     * 
     */
    public PmcXmlJournalId createPmcXmlJournalId() {
        return new PmcXmlJournalId();
    }

    /**
     * Create an instance of {@link PmcXmlStringDate }
     * 
     */
    public PmcXmlStringDate createPmcXmlStringDate() {
        return new PmcXmlStringDate();
    }

    /**
     * Create an instance of {@link PmcXmlSubjGroup }
     * 
     */
    public PmcXmlSubjGroup createPmcXmlSubjGroup() {
        return new PmcXmlSubjGroup();
    }

    /**
     * Create an instance of {@link PmcXmlSubject }
     * 
     */
    public PmcXmlSubject createPmcXmlSubject() {
        return new PmcXmlSubject();
    }

    /**
     * Create an instance of {@link PmcXmlSeriesText }
     * 
     */
    public PmcXmlSeriesText createPmcXmlSeriesText() {
        return new PmcXmlSeriesText();
    }

    /**
     * Create an instance of {@link PmcXmlPubDate }
     * 
     */
    public PmcXmlPubDate createPmcXmlPubDate() {
        return new PmcXmlPubDate();
    }

    /**
     * Create an instance of {@link PmcXmlCustomMeta }
     * 
     */
    public PmcXmlCustomMeta createPmcXmlCustomMeta() {
        return new PmcXmlCustomMeta();
    }

    /**
     * Create an instance of {@link PmcXmlMetaValue }
     * 
     */
    public PmcXmlMetaValue createPmcXmlMetaValue() {
        return new PmcXmlMetaValue();
    }

    /**
     * Create an instance of {@link PmcXmlTableCount }
     * 
     */
    public PmcXmlTableCount createPmcXmlTableCount() {
        return new PmcXmlTableCount();
    }

    /**
     * Create an instance of {@link PmcXmlUnstructuredKwdGroup }
     * 
     */
    public PmcXmlUnstructuredKwdGroup createPmcXmlUnstructuredKwdGroup() {
        return new PmcXmlUnstructuredKwdGroup();
    }

    /**
     * Create an instance of {@link PmcXmlAwardGroup }
     * 
     */
    public PmcXmlAwardGroup createPmcXmlAwardGroup() {
        return new PmcXmlAwardGroup();
    }

    /**
     * Create an instance of {@link PmcXmlPrincipalAwardRecipient }
     * 
     */
    public PmcXmlPrincipalAwardRecipient createPmcXmlPrincipalAwardRecipient() {
        return new PmcXmlPrincipalAwardRecipient();
    }

    /**
     * Create an instance of {@link PmcXmlPrincipalInvestigator }
     * 
     */
    public PmcXmlPrincipalInvestigator createPmcXmlPrincipalInvestigator() {
        return new PmcXmlPrincipalInvestigator();
    }

    /**
     * Create an instance of {@link PmcXmlUnderlineStart }
     * 
     */
    public PmcXmlUnderlineStart createPmcXmlUnderlineStart() {
        return new PmcXmlUnderlineStart();
    }

    /**
     * Create an instance of {@link PmcXmlUnderlineEnd }
     * 
     */
    public PmcXmlUnderlineEnd createPmcXmlUnderlineEnd() {
        return new PmcXmlUnderlineEnd();
    }

    /**
     * Create an instance of {@link PmcXmlJournalTitleGroup }
     * 
     */
    public PmcXmlJournalTitleGroup createPmcXmlJournalTitleGroup() {
        return new PmcXmlJournalTitleGroup();
    }

    /**
     * Create an instance of {@link PmcXmlJournalTitle }
     * 
     */
    public PmcXmlJournalTitle createPmcXmlJournalTitle() {
        return new PmcXmlJournalTitle();
    }

    /**
     * Create an instance of {@link PmcXmlJournalSubtitle }
     * 
     */
    public PmcXmlJournalSubtitle createPmcXmlJournalSubtitle() {
        return new PmcXmlJournalSubtitle();
    }

    /**
     * Create an instance of {@link PmcXmlTransTitleGroup }
     * 
     */
    public PmcXmlTransTitleGroup createPmcXmlTransTitleGroup() {
        return new PmcXmlTransTitleGroup();
    }

    /**
     * Create an instance of {@link PmcXmlTransSubtitle }
     * 
     */
    public PmcXmlTransSubtitle createPmcXmlTransSubtitle() {
        return new PmcXmlTransSubtitle();
    }

    /**
     * Create an instance of {@link PmcXmlAbbrevJournalTitle }
     * 
     */
    public PmcXmlAbbrevJournalTitle createPmcXmlAbbrevJournalTitle() {
        return new PmcXmlAbbrevJournalTitle();
    }

    /**
     * Create an instance of {@link PmcXmlBack }
     * 
     */
    public PmcXmlBack createPmcXmlBack() {
        return new PmcXmlBack();
    }

    /**
     * Create an instance of {@link PmcXmlAck }
     * 
     */
    public PmcXmlAck createPmcXmlAck() {
        return new PmcXmlAck();
    }

    /**
     * Create an instance of {@link PmcXmlAppGroup }
     * 
     */
    public PmcXmlAppGroup createPmcXmlAppGroup() {
        return new PmcXmlAppGroup();
    }

    /**
     * Create an instance of {@link PmcXmlApp }
     * 
     */
    public PmcXmlApp createPmcXmlApp() {
        return new PmcXmlApp();
    }

    /**
     * Create an instance of {@link PmcXmlNotes }
     * 
     */
    public PmcXmlNotes createPmcXmlNotes() {
        return new PmcXmlNotes();
    }

    /**
     * Create an instance of {@link PmcXmlFront }
     * 
     */
    public PmcXmlFront createPmcXmlFront() {
        return new PmcXmlFront();
    }

    /**
     * Create an instance of {@link PmcXmlJournalMeta }
     * 
     */
    public PmcXmlJournalMeta createPmcXmlJournalMeta() {
        return new PmcXmlJournalMeta();
    }

    /**
     * Create an instance of {@link PmcXmlPublisher }
     * 
     */
    public PmcXmlPublisher createPmcXmlPublisher() {
        return new PmcXmlPublisher();
    }

    /**
     * Create an instance of {@link PmcXmlArticleMeta }
     * 
     */
    public PmcXmlArticleMeta createPmcXmlArticleMeta() {
        return new PmcXmlArticleMeta();
    }

    /**
     * Create an instance of {@link PmcXmlArticleId }
     * 
     */
    public PmcXmlArticleId createPmcXmlArticleId() {
        return new PmcXmlArticleId();
    }

    /**
     * Create an instance of {@link PmcXmlArticleCategories }
     * 
     */
    public PmcXmlArticleCategories createPmcXmlArticleCategories() {
        return new PmcXmlArticleCategories();
    }

    /**
     * Create an instance of {@link PmcXmlSeriesTitle }
     * 
     */
    public PmcXmlSeriesTitle createPmcXmlSeriesTitle() {
        return new PmcXmlSeriesTitle();
    }

    /**
     * Create an instance of {@link PmcXmlTitleGroup }
     * 
     */
    public PmcXmlTitleGroup createPmcXmlTitleGroup() {
        return new PmcXmlTitleGroup();
    }

    /**
     * Create an instance of {@link PmcXmlAltTitle }
     * 
     */
    public PmcXmlAltTitle createPmcXmlAltTitle() {
        return new PmcXmlAltTitle();
    }

    /**
     * Create an instance of {@link PmcXmlAuthorNotes }
     * 
     */
    public PmcXmlAuthorNotes createPmcXmlAuthorNotes() {
        return new PmcXmlAuthorNotes();
    }

    /**
     * Create an instance of {@link PmcXmlCorresp }
     * 
     */
    public PmcXmlCorresp createPmcXmlCorresp() {
        return new PmcXmlCorresp();
    }

    /**
     * Create an instance of {@link PmcXmlIssueSponsor }
     * 
     */
    public PmcXmlIssueSponsor createPmcXmlIssueSponsor() {
        return new PmcXmlIssueSponsor();
    }

    /**
     * Create an instance of {@link PmcXmlHistory }
     * 
     */
    public PmcXmlHistory createPmcXmlHistory() {
        return new PmcXmlHistory();
    }

    /**
     * Create an instance of {@link PmcXmlSelfUri }
     * 
     */
    public PmcXmlSelfUri createPmcXmlSelfUri() {
        return new PmcXmlSelfUri();
    }

    /**
     * Create an instance of {@link PmcXmlAbstract }
     * 
     */
    public PmcXmlAbstract createPmcXmlAbstract() {
        return new PmcXmlAbstract();
    }

    /**
     * Create an instance of {@link PmcXmlTransAbstract }
     * 
     */
    public PmcXmlTransAbstract createPmcXmlTransAbstract() {
        return new PmcXmlTransAbstract();
    }

    /**
     * Create an instance of {@link PmcXmlFundingGroup }
     * 
     */
    public PmcXmlFundingGroup createPmcXmlFundingGroup() {
        return new PmcXmlFundingGroup();
    }

    /**
     * Create an instance of {@link PmcXmlFundingStatement }
     * 
     */
    public PmcXmlFundingStatement createPmcXmlFundingStatement() {
        return new PmcXmlFundingStatement();
    }

    /**
     * Create an instance of {@link PmcXmlConference }
     * 
     */
    public PmcXmlConference createPmcXmlConference() {
        return new PmcXmlConference();
    }

    /**
     * Create an instance of {@link PmcXmlConfAcronym }
     * 
     */
    public PmcXmlConfAcronym createPmcXmlConfAcronym() {
        return new PmcXmlConfAcronym();
    }

    /**
     * Create an instance of {@link PmcXmlConfNum }
     * 
     */
    public PmcXmlConfNum createPmcXmlConfNum() {
        return new PmcXmlConfNum();
    }

    /**
     * Create an instance of {@link PmcXmlConfTheme }
     * 
     */
    public PmcXmlConfTheme createPmcXmlConfTheme() {
        return new PmcXmlConfTheme();
    }

    /**
     * Create an instance of {@link PmcXmlCounts }
     * 
     */
    public PmcXmlCounts createPmcXmlCounts() {
        return new PmcXmlCounts();
    }

    /**
     * Create an instance of {@link PmcXmlFigCount }
     * 
     */
    public PmcXmlFigCount createPmcXmlFigCount() {
        return new PmcXmlFigCount();
    }

    /**
     * Create an instance of {@link PmcXmlEquationCount }
     * 
     */
    public PmcXmlEquationCount createPmcXmlEquationCount() {
        return new PmcXmlEquationCount();
    }

    /**
     * Create an instance of {@link PmcXmlRefCount }
     * 
     */
    public PmcXmlRefCount createPmcXmlRefCount() {
        return new PmcXmlRefCount();
    }

    /**
     * Create an instance of {@link PmcXmlWordCount }
     * 
     */
    public PmcXmlWordCount createPmcXmlWordCount() {
        return new PmcXmlWordCount();
    }

    /**
     * Create an instance of {@link PmcXmlCustomMetaGroup }
     * 
     */
    public PmcXmlCustomMetaGroup createPmcXmlCustomMetaGroup() {
        return new PmcXmlCustomMetaGroup();
    }

    /**
     * Create an instance of {@link PmcXmlX }
     * 
     */
    public PmcXmlX createPmcXmlX() {
        return new PmcXmlX();
    }

    /**
     * Create an instance of {@link PmcXmlSig }
     * 
     */
    public PmcXmlSig createPmcXmlSig() {
        return new PmcXmlSig();
    }

    /**
     * Create an instance of {@link PmcXmlBody }
     * 
     */
    public PmcXmlBody createPmcXmlBody() {
        return new PmcXmlBody();
    }

    /**
     * Create an instance of {@link PmcXmlSigBlock }
     * 
     */
    public PmcXmlSigBlock createPmcXmlSigBlock() {
        return new PmcXmlSigBlock();
    }

    /**
     * Create an instance of {@link PmcXmlResponse }
     * 
     */
    public PmcXmlResponse createPmcXmlResponse() {
        return new PmcXmlResponse();
    }

    /**
     * Create an instance of {@link PmcXmlFrontStub }
     * 
     */
    public PmcXmlFrontStub createPmcXmlFrontStub() {
        return new PmcXmlFrontStub();
    }

    /**
     * Create an instance of {@link PmcXmlFloatsGroup }
     * 
     */
    public PmcXmlFloatsGroup createPmcXmlFloatsGroup() {
        return new PmcXmlFloatsGroup();
    }

    /**
     * Create an instance of {@link PmcXmlSubArticle }
     * 
     */
    public PmcXmlSubArticle createPmcXmlSubArticle() {
        return new PmcXmlSubArticle();
    }

    /**
     * Create an instance of {@link PmcXmlStringConf }
     * 
     */
    public PmcXmlStringConf createPmcXmlStringConf() {
        return new PmcXmlStringConf();
    }

    /**
     * Create an instance of {@link PmcXmlOverlineStart }
     * 
     */
    public PmcXmlOverlineStart createPmcXmlOverlineStart() {
        return new PmcXmlOverlineStart();
    }

    /**
     * Create an instance of {@link PmcXmlArticle }
     * 
     */
    public PmcXmlArticle createPmcXmlArticle() {
        return new PmcXmlArticle();
    }

    /**
     * Create an instance of {@link PmcXmlOverlineEnd }
     * 
     */
    public PmcXmlOverlineEnd createPmcXmlOverlineEnd() {
        return new PmcXmlOverlineEnd();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "surname")
    public JAXBElement<String> createSurname(String value) {
        return new JAXBElement<String>(_Surname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "given-names")
    public JAXBElement<String> createGivenNames(String value) {
        return new JAXBElement<String>(_GivenNames_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "etal")
    public JAXBElement<String> createEtal(String value) {
        return new JAXBElement<String>(_Etal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "meta-name")
    public JAXBElement<String> createMetaName(String value) {
        return new JAXBElement<String>(_MetaName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "publisher-name")
    public JAXBElement<String> createPublisherName(String value) {
        return new JAXBElement<String>(_PublisherName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "prefix")
    public JAXBElement<String> createPrefix(String value) {
        return new JAXBElement<String>(_Prefix_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "issue-part")
    public JAXBElement<String> createIssuePart(String value) {
        return new JAXBElement<String>(_IssuePart_QNAME, String.class, null, value);
    }

}
