//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice minOccurs="0">
 *           &lt;sequence>
 *             &lt;element ref="{}day" minOccurs="0"/>
 *             &lt;element ref="{}month" minOccurs="0"/>
 *           &lt;/sequence>
 *           &lt;element ref="{}season"/>
 *         &lt;/choice>
 *         &lt;element ref="{}year"/>
 *       &lt;/sequence>
 *       &lt;attribute name="date-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "season",
    "day",
    "month",
    "year"
})
@XmlRootElement(name = "date")
public class PmcXmlDate {

    protected PmcXmlSeason season;
    protected PmcXmlDay day;
    protected PmcXmlMonth month;
    @XmlElement(required = true)
    protected PmcXmlYear year;
    @XmlAttribute(name = "date-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String dateType;

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlSeason }
     *     
     */
    public PmcXmlSeason getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlSeason }
     *     
     */
    public void setSeason(PmcXmlSeason value) {
        this.season = value;
    }

    /**
     * Gets the value of the day property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlDay }
     *     
     */
    public PmcXmlDay getDay() {
        return day;
    }

    /**
     * Sets the value of the day property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlDay }
     *     
     */
    public void setDay(PmcXmlDay value) {
        this.day = value;
    }

    /**
     * Gets the value of the month property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlMonth }
     *     
     */
    public PmcXmlMonth getMonth() {
        return month;
    }

    /**
     * Sets the value of the month property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlMonth }
     *     
     */
    public void setMonth(PmcXmlMonth value) {
        this.month = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlYear }
     *     
     */
    public PmcXmlYear getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlYear }
     *     
     */
    public void setYear(PmcXmlYear value) {
        this.year = value;
    }

    /**
     * Gets the value of the dateType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateType() {
        return dateType;
    }

    /**
     * Sets the value of the dateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateType(String value) {
        this.dateType = value;
    }

}
