//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;choice>
 *           &lt;element ref="{}glyph-data"/>
 *           &lt;element ref="{}glyph-ref"/>
 *         &lt;/choice>
 *         &lt;element ref="{}inline-graphic" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inlineGraphics",
    "glyphRef",
    "glyphData"
})
@XmlRootElement(name = "private-char")
public class PmcXmlPrivateChar {

    @XmlElement(name = "inline-graphic")
    protected List<PmcXmlInlineGraphic> inlineGraphics;
    @XmlElement(name = "glyph-ref")
    protected PmcXmlGlyphRef glyphRef;
    @XmlElement(name = "glyph-data")
    protected PmcXmlGlyphData glyphData;
    @XmlAttribute(name = "description")
    @XmlSchemaType(name = "anySimpleType")
    protected String description;
    @XmlAttribute(name = "name")
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the inlineGraphics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inlineGraphics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInlineGraphics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmcXmlInlineGraphic }
     * 
     * 
     */
    public List<PmcXmlInlineGraphic> getInlineGraphics() {
        if (inlineGraphics == null) {
            inlineGraphics = new ArrayList<PmcXmlInlineGraphic>();
        }
        return this.inlineGraphics;
    }

    /**
     * Gets the value of the glyphRef property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlGlyphRef }
     *     
     */
    public PmcXmlGlyphRef getGlyphRef() {
        return glyphRef;
    }

    /**
     * Sets the value of the glyphRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlGlyphRef }
     *     
     */
    public void setGlyphRef(PmcXmlGlyphRef value) {
        this.glyphRef = value;
    }

    /**
     * Gets the value of the glyphData property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlGlyphData }
     *     
     */
    public PmcXmlGlyphData getGlyphData() {
        return glyphData;
    }

    /**
     * Sets the value of the glyphData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlGlyphData }
     *     
     */
    public void setGlyphData(PmcXmlGlyphData value) {
        this.glyphData = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
