//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}title" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element ref="{}p"/>
 *           &lt;element ref="{}fn-group"/>
 *           &lt;element ref="{}fn"/>
 *           &lt;element ref="{}attrib"/>
 *           &lt;element ref="{}permissions"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "psAndFnGroupsAndFns"
})
@XmlRootElement(name = "table-wrap-foot")
public class PmcXmlTableWrapFoot {

    protected PmcXmlTitle title;
    @XmlElements({
        @XmlElement(name = "p", type = PmcXmlP.class),
        @XmlElement(name = "fn-group", type = PmcXmlFnGroup.class),
        @XmlElement(name = "fn", type = PmcXmlFn.class),
        @XmlElement(name = "attrib", type = PmcXmlAttrib.class),
        @XmlElement(name = "permissions", type = PmcXmlPermissions.class)
    })
    protected List<Object> psAndFnGroupsAndFns;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlTitle }
     *     
     */
    public PmcXmlTitle getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlTitle }
     *     
     */
    public void setTitle(PmcXmlTitle value) {
        this.title = value;
    }

    /**
     * Gets the value of the psAndFnGroupsAndFns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the psAndFnGroupsAndFns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPSAndFnGroupsAndFns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmcXmlP }
     * {@link PmcXmlFnGroup }
     * {@link PmcXmlFn }
     * {@link PmcXmlAttrib }
     * {@link PmcXmlPermissions }
     * 
     * 
     */
    public List<Object> getPSAndFnGroupsAndFns() {
        if (psAndFnGroupsAndFns == null) {
            psAndFnGroupsAndFns = new ArrayList<Object>();
        }
        return this.psAndFnGroupsAndFns;
    }

}
