//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import edu.isi.bmkeg.lapdf.pmcXml.mathml.PmcXmlMath;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}array"/>
 *         &lt;element ref="{}chem-struct"/>
 *         &lt;element ref="{}graphic"/>
 *         &lt;element ref="{}inline-graphic"/>
 *         &lt;element ref="{}inline-supplementary-material"/>
 *         &lt;element ref="{}media"/>
 *         &lt;element ref="{}textual-form"/>
 *         &lt;element ref="{}preformat"/>
 *         &lt;element ref="{}private-char"/>
 *         &lt;element ref="{}supplementary-material"/>
 *         &lt;element ref="{}table"/>
 *         &lt;element ref="{}tex-math"/>
 *         &lt;element ref="{http://www.w3.org/1998/Math/MathML}math"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "arraiesAndChemStructsAndGraphics"
})
@XmlRootElement(name = "alternatives")
public class PmcXmlAlternatives {

    @XmlElements({
        @XmlElement(name = "array", type = PmcXmlArray.class),
        @XmlElement(name = "chem-struct", type = PmcXmlChemStruct.class),
        @XmlElement(name = "graphic", type = PmcXmlGraphic.class),
        @XmlElement(name = "inline-graphic", type = PmcXmlInlineGraphic.class),
        @XmlElement(name = "inline-supplementary-material", type = PmcXmlInlineSupplementaryMaterial.class),
        @XmlElement(name = "media", type = PmcXmlMedia.class),
        @XmlElement(name = "textual-form", type = PmcXmlTextualForm.class),
        @XmlElement(name = "preformat", type = PmcXmlPreformat.class),
        @XmlElement(name = "private-char", type = PmcXmlPrivateChar.class),
        @XmlElement(name = "supplementary-material", type = PmcXmlSupplementaryMaterial.class),
        @XmlElement(name = "table", type = PmcXmlTable.class),
        @XmlElement(name = "tex-math", type = PmcXmlTexMath.class),
        @XmlElement(name = "math", namespace = "http://www.w3.org/1998/Math/MathML", type = PmcXmlMath.class)
    })
    protected List<Object> arraiesAndChemStructsAndGraphics;

    /**
     * Gets the value of the arraiesAndChemStructsAndGraphics property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the arraiesAndChemStructsAndGraphics property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArraiesAndChemStructsAndGraphics().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmcXmlArray }
     * {@link PmcXmlChemStruct }
     * {@link PmcXmlGraphic }
     * {@link PmcXmlInlineGraphic }
     * {@link PmcXmlInlineSupplementaryMaterial }
     * {@link PmcXmlMedia }
     * {@link PmcXmlTextualForm }
     * {@link PmcXmlPreformat }
     * {@link PmcXmlPrivateChar }
     * {@link PmcXmlSupplementaryMaterial }
     * {@link PmcXmlTable }
     * {@link PmcXmlTexMath }
     * {@link PmcXmlMath }
     * 
     * 
     */
    public List<Object> getArraiesAndChemStructsAndGraphics() {
        if (arraiesAndChemStructsAndGraphics == null) {
            arraiesAndChemStructsAndGraphics = new ArrayList<Object>();
        }
        return this.arraiesAndChemStructsAndGraphics;
    }

}
