//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}journal-meta"/>
 *         &lt;element ref="{}article-meta"/>
 *         &lt;element ref="{}notes" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journalMeta",
    "articleMeta",
    "notes"
})
@XmlRootElement(name = "front")
public class PmcXmlFront {

    @XmlElement(name = "journal-meta", required = true)
    protected PmcXmlJournalMeta journalMeta;
    @XmlElement(name = "article-meta", required = true)
    protected PmcXmlArticleMeta articleMeta;
    protected PmcXmlNotes notes;

    /**
     * Gets the value of the journalMeta property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlJournalMeta }
     *     
     */
    public PmcXmlJournalMeta getJournalMeta() {
        return journalMeta;
    }

    /**
     * Sets the value of the journalMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlJournalMeta }
     *     
     */
    public void setJournalMeta(PmcXmlJournalMeta value) {
        this.journalMeta = value;
    }

    /**
     * Gets the value of the articleMeta property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlArticleMeta }
     *     
     */
    public PmcXmlArticleMeta getArticleMeta() {
        return articleMeta;
    }

    /**
     * Sets the value of the articleMeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlArticleMeta }
     *     
     */
    public void setArticleMeta(PmcXmlArticleMeta value) {
        this.articleMeta = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link PmcXmlNotes }
     *     
     */
    public PmcXmlNotes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link PmcXmlNotes }
     *     
     */
    public void setNotes(PmcXmlNotes value) {
        this.notes = value;
    }

}
