//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.23 at 10:09:05 AM PDT 
//


package edu.isi.bmkeg.lapdf.pmcXml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}alternatives"/>
 *         &lt;element ref="{}boxed-text"/>
 *         &lt;element ref="{}chem-struct-wrap"/>
 *         &lt;element ref="{}fig"/>
 *         &lt;element ref="{}fig-group"/>
 *         &lt;element ref="{}graphic"/>
 *         &lt;element ref="{}media"/>
 *         &lt;element ref="{}preformat"/>
 *         &lt;element ref="{}supplementary-material"/>
 *         &lt;element ref="{}table-wrap"/>
 *         &lt;element ref="{}table-wrap-group"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "alternativesAndBoxedTextsAndChemStructWraps"
})
@XmlRootElement(name = "floats-group")
public class PmcXmlFloatsGroup {

    @XmlElements({
        @XmlElement(name = "alternatives", type = PmcXmlAlternatives.class),
        @XmlElement(name = "boxed-text", type = PmcXmlBoxedText.class),
        @XmlElement(name = "chem-struct-wrap", type = PmcXmlChemStructWrap.class),
        @XmlElement(name = "fig", type = PmcXmlFig.class),
        @XmlElement(name = "fig-group", type = PmcXmlFigGroup.class),
        @XmlElement(name = "graphic", type = PmcXmlGraphic.class),
        @XmlElement(name = "media", type = PmcXmlMedia.class),
        @XmlElement(name = "preformat", type = PmcXmlPreformat.class),
        @XmlElement(name = "supplementary-material", type = PmcXmlSupplementaryMaterial.class),
        @XmlElement(name = "table-wrap", type = PmcXmlTableWrap.class),
        @XmlElement(name = "table-wrap-group", type = PmcXmlTableWrapGroup.class)
    })
    protected List<Object> alternativesAndBoxedTextsAndChemStructWraps;

    /**
     * Gets the value of the alternativesAndBoxedTextsAndChemStructWraps property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alternativesAndBoxedTextsAndChemStructWraps property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlternativesAndBoxedTextsAndChemStructWraps().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PmcXmlAlternatives }
     * {@link PmcXmlBoxedText }
     * {@link PmcXmlChemStructWrap }
     * {@link PmcXmlFig }
     * {@link PmcXmlFigGroup }
     * {@link PmcXmlGraphic }
     * {@link PmcXmlMedia }
     * {@link PmcXmlPreformat }
     * {@link PmcXmlSupplementaryMaterial }
     * {@link PmcXmlTableWrap }
     * {@link PmcXmlTableWrapGroup }
     * 
     * 
     */
    public List<Object> getAlternativesAndBoxedTextsAndChemStructWraps() {
        if (alternativesAndBoxedTextsAndChemStructWraps == null) {
            alternativesAndBoxedTextsAndChemStructWraps = new ArrayList<Object>();
        }
        return this.alternativesAndBoxedTextsAndChemStructWraps;
    }

}
